### ISSUE TITLE
gl-react-image: center and zoom props are only supported with resizeMode='cover'

### ISSUE THREAD

**Issue by StevenKing9** [stoffern/react-native-image-cropper#10]
this is  not  a bug . it's a function support. I think it's very important.
Because if the image width(or height)  is so long .
Can‘t  show a full image when the starting to end . 
can't  reduce image.

**Comment by stoffern** [comment]
@StevenKing9 that is the point of the cropping.
it will either zoom to fill width or height so that the image will cover the cropping area.

Dont think i really understand what is your question?
