### ISSUE TITLE
panToMove doesn't work on iOS

### ISSUE THREAD

**Issue by alexmngn** [stoffern/react-native-image-cropper#15]
While trying to "panToMove" the image, I got the following error when zoom is set to default value

<img width="617" alt="screen shot 2016-08-20 at 11 25 51" src="https://cloud.githubusercontent.com/assets/4203845/17833103/9eaaa15c-66c9-11e6-8f79-105a034c2010.png">

Also, I can't make the `pinchToZoom` to work on iOS as well with an image source coming from CameraRoll (I use data base64 image). I've tried to set different `zoom`, `maxZoom` and `minZoom` values, the pinch won't work.

**Comment by stoffern** [comment]
Have you tried with a image that is not base 64?

**Comment by anotherstarburst** [comment]
Getting the same problem using image from simulators camera roll. Not sure how to get an image that's not base 64?

**Comment by stoffern** [comment]
should be fixed here: 6aba9b57c9bb3e158f59e66ea8fd1ff3cf4b4fa9
