### ISSUE TITLE
Expected a string but got object error

### ISSUE THREAD

**Issue by magrinj** [stoffern/react-native-image-cropper#17]
I got this error when I want to use the `ImageCropper` component:

```jsx
      <View style={{ flex: 1 }}>
        <ImageCropper
          ref="cropper"
          image={source} // string
          cropHeight={height} // number
          cropWidth={width} // number
          zoom={50}
          maxZoom={70}
          minZoom={10}
          panToMove={true}
          pinchToZoom={true}/>
        <Text onPress={this._capture.bind(this)}>Capture</Text>
      </View>
```

<img width="354" alt="screen shot 2016-09-26 at 5 00 41 pm" src="https://cloud.githubusercontent.com/assets/3551795/18839304/c9c8be06-840a-11e6-94bb-03c92513d1d2.png">

I print in my console the values of `image`, `cropHeight` and `cropWidth` and they are good, the problem happen also if I put static value directly in the component jsx

**Comment by stoffern** [comment]
```js
import {ImageCrop} from 'react-native-image-cropper' 
```

**Comment by magrinj** [comment]
Thanks, working now, I didn't the way the import need to be done
