### ISSUE TITLE
New release needed

### ISSUE THREAD

**Issue by alexsegura** [stoffern/react-native-image-cropper#18]
A new release is needed to work with latest React versions, following 0f0abae7ad4451cf90d9dfe7e4a9e8c215af0380

Version `0.1.10` does not work, it complains about duplicate packages. 

Can you please make a new release?

**Comment by stoffern** [comment]
Will be updated not with this fix:
6aba9b57c9bb3e158f59e66ea8fd1ff3cf4b4fa9
