### ISSUE TITLE
Shader '(gl-react-post)': uniform 't' Shader #2 does not exists

### ISSUE THREAD

**Issue by tinchogon34** [stoffern/react-native-image-cropper#19]
I'm using react-native 0.39 with gl-react 3.0.0 and gl-react-native 2.39.0, and I can't make this library work, I've already tried downgrading react-native and another libraries but nothing works. Here is the error

![image](https://cloud.githubusercontent.com/assets/1757985/21030409/0ffd5e4e-bd7d-11e6-95bc-090a3f6e4d71.png)

Any help will be appreciated!

**Comment by stoffern** [comment]
@tinchogon34 can you provide the code aswell?
ios or android?

**Comment by codingwaysarg** [comment]
Later I could upload the code. But it's a copy of this component https://github.com/stoffern/react-native-image-cropper/blob/master/example/index.js.

For now the error it's in Android. I haven't tried iOS

**Comment by stoffern** [comment]
are you the same person? 😄 
Well i will give it a try to see if it errors..

**Comment by stoffern** [comment]
I added a full example and it works just fine ;)

Looks like you are using a custom shader inside the code where: uniform "t" is not provided.

**Comment by tinchogon34** [comment]
Thanks @stoffern ! Finally it was a problem of versions, somewhere in react-native or gl-* libraries, because I replace whole node_modules from complete example and started working.
