### ISSUE TITLE
Zoom not working inside Modal (Android)

### ISSUE THREAD

**Issue by tinchogon34** [stoffern/react-native-image-cropper#20]
Hi, I'm trying to use this library inside Modal component and pinchToZoom doesn't works at all.

I've tried modifying full example code and the problem still happen.

```
      <Modal
        animationType={"slide"}
        transparent={false}
        visible={true}
        onRequestClose={() => {this.setState({modalVisible: false, cropImage: {}})}}
        >
          <ImageCrop
            ref={'cropper'}
            image={this.state.image}
            cropHeight={this.state.height}
            cropWidth={this.state.width}
            zoom={80}
            maxZoom={80}
            minZoom={80}
            panToMove={true}
            pinchToZoom={true}
          />
      </Modal>
```

**Comment by tinchogon34** [comment]
Inside modal, when 2nd finger touch the screen the onPanResponderTerminate event is fired. 

Maybe something with _shouldSetResponder in line 178?

[https://github.com/facebook/react-native/blob/4530da87e296a3043c9176a7f2b1bfa0f42489ee/Libraries/Modal/Modal.js](url)

**Comment by tinchogon34** [comment]
Setting 

> onPanResponderTerminationRequest: (evt, gestureState) => false

in line [93](https://github.com/stoffern/react-native-image-cropper/blob/master/src/ImageCrop.js#L93) of source code make it work. 
Another component is claiming the responder when 2nd touch start.

**Comment by stoffern** [comment]
tnx for reporting 😉
