### ISSUE TITLE
Example App: Failed to get size for image

### ISSUE THREAD

**Issue by gregorykan** [stoffern/react-native-image-cropper#21]
Hi there! Am trying out the example app/code, and keep getting the following error:

Failed to get size for image: http://i.imgur.com/tCatS2c.jpg

Any idea what I might be doing wrong?

**Comment by gregorykan** [comment]
this may be due to https://github.com/facebook/react-native/issues/8520

**Comment by stoffern** [comment]
New to app development? 😉 
This is the most common issue developing with IOS.
Apple enforce HTTPS to all apps, you need to allow HTTP if you want it to work.

You can do that by adding: 
```
<key>NSAppTransportSecurity</key>
<dict>
    <key>NSAllowsArbitraryLoads</key>
    <true/>
</dict>
```
to the Info.plist or in Xcode..
