### ISSUE TITLE
Screen size ratio

### ISSUE THREAD

**Issue by danrice01** [stoffern/react-native-image-cropper#22]
Thanks for building this @stoffern, I tried every available RN crop package before this and yours was the only one that offered actual useful cropping capabilities.

I have a question though - do you know if it's possible to do the cropping based on the natural size of the image, but display the crop dialog as a ratio based on the screen size?

For example, an image is 1080 x 1080 and we want the crop area to be 1080 x 540. However if we specify this using `cropHeight` and `cropWidth`, the image is too big for the screen. We solve this when displaying the image normally, by using a ratio and screen size, however we can't do this when cropping as the resulting base64 image is output at the ratio size, not the actual size. Are you able to suggest a solution to this using react-native-image-cropper?

**Comment by stoffern** [comment]
@danrice01 Good question, this is possible to do, but not right now.
`gl-react` support a variable for this that will set the pixelratio on capture.
I will add the feature this weekend.

**Comment by danrice01** [comment]
@stoffern Fantastic, I look forward to that feature addition :)

**Comment by stoffern** [comment]
@danrice01 added here: b26273c3d2fbf920ef998a6ed6612a71f2ff70bf
For more reference see gl-react and gl-react-native on `pixelRatio`

**Comment by tinchogon34** [comment]
@danrice01 did you solve the problem?
