### ISSUE TITLE
Problem with crop size

### ISSUE THREAD

**Issue by tinchogon34** [stoffern/react-native-image-cropper#27]
I think my problem it's related to #22. 
I've an image that I need to crop to a size bigger than the screen, so I pass the props cropWidth and cropHeight to 800 x 600 respectively. With the pixelRatio feature (without touching default value), the image show in full screen but I can't scroll fluid inside it to select crop section. I probably need the image showing scaled proportionally in the crop modal, and then the user should zoom and crop the desired section.

Is this possible? I've trying a lot to work around this but I can't.

**Comment by stoffern** [comment]
Dont know if i understand your question.
If you set pixelRatio to 2 times the default then your image should also be twise as big.
pixelRatio={PixelRatio.get()*2}

ref:
https://facebook.github.io/react-native/docs/pixelratio.html#methods

**Comment by tinchogon34** [comment]
The problem is that I need to crop images to a size bigger than the screen. I need to send to cropWidth and cropHeight sizes bigger than the screen but still render the image (keeping aspect ratio) between the screen dimensions.

**Comment by tinchogon34** [comment]
Will try, thanks!
