### ISSUE TITLE
RCTImageLoader 

### ISSUE THREAD

**Issue by clovs** [stoffern/react-native-image-cropper#28]
Hello guys,
I just update all my project to react-native 0.40, and
I'm trying to use your package but I got this error on xcode:
[RCTImageLoader _loadImageOrDataWithURLRequest:size:scale:resizeMode:progressBlock:partialLoadBlock:completionBlock:]_block_invoke.194 + 355
libc++abi.dylib: terminating with uncaught exception of type NSException

My dependencies: {
    "gl-react": "^2.2.4",
    "gl-react-image": "0.0.2",
    "gl-react-native": "^2.40.1",
    "react": "15.4.2",
    "react-native": "<=0.40.0",
    "react-native-camera": "git+https://github.com/lwansbrough/react-native-camera.git",
    "react-native-image-cropper": "^0.3.0",
    "react-native-router-flux": "^3.37.0"
  }
Hope you can help me
regards,

**Comment by clovs** [comment]
Issue Solved few days after with npm i
;-)

**Comment by stoffern** [comment]
clovs = clown? 😆
