### ISSUE TITLE
Add support for draggable box?

### ISSUE THREAD

**Issue by clovs** [stoffern/react-native-image-cropper#29]
Hello @stoffern,
It's Clovs the Clown ;-)

Will you add a feature to your component, where the image is stationary with a draggable box represents the cropped image in react-native. 
example on this image: 
https://i1.wp.com/reactscript.com/wp-content/uploads/2016/07/Accessible-Image-Cropper-For-React.png

Cause there is no third library that do that (with IOS and Android compatibility).
Actually your component is the best in cropping picture on react-native, that why I ask you that.
Maybe I will help you in few month but I need some time to learn React for now :-P

See you around
regards,

**Comment by stoffern** [comment]
hehe 😉 
I will not add that feature as it is not a good solution to use on mobile units.
I can see that it would be nice on pads, but this feature or option should be a seperate react component.

sorry 😞
