### ISSUE TITLE
Add support for local image cropping

### ISSUE THREAD

**Issue by stoffern** [stoffern/react-native-image-cropper#3]
require ('.image.jpg')

**Comment by FearMediocrity** [comment]
This would be a massive win.

**Comment by stoffern** [comment]
@FearMediocrity There is a workaround for this:

```js
const resolveAssetSource = require("react-native/Libraries/Image/resolveAssetSource");
const imageUri = resolveAssetSource(require("./Image.jpg"))

<ImageCrop 
  image={imageUri}
/>
```

**Comment by sibelius** [comment]
@stoffern is there a workaround for the case of an asset, like this:

assets-library://asset/asset.JPG?id=B84E8479-475C-4727-A4A4-B77AA9980897&ext=JPG

a photo from camera roll for instance

**Comment by stoffern** [comment]
@sibelius you need the real path for the image, what you have there is the MEDIASTORE content string from the assets-library. https://github.com/Wraptime/react-native-get-real-path

**Comment by sibelius** [comment]
this package only works on android not ios

**Comment by stoffern** [comment]
@sibelius add a request to `react-native-get-real-path` to develop it for iOS.
I dont quite have the time to do this now.

This is also not a issue for react-native-image-cropper as files that are provided should always be real path objects

**Comment by kolya3001** [comment]
@sibelius i have a workaround for ios:

1. Convert image to base64 using this: https://github.com/wootwoot1234/react-native-asset-library-to-base64
2. Add 'data:image/png;base64,' at the start of your base64 string
3. Use it with react-native-image-cropper

Hope this will help

**Comment by stoffern** [comment]
Problem is solved with this workaround https://github.com/stoffern/react-native-image-cropper/issues/3#issuecomment-230726453, other fixes will not me made.
