### ISSUE TITLE
"gl-react-native: the native module is not available."

### ISSUE THREAD

**Issue by bkotos** [stoffern/react-native-image-cropper#32]
Hello,

I'm trying to use `react-native-image-cropper` in my react-native app for ios.  When I import the package
```javascript
import { ImageCrop } from 'react-native-image-cropper';
```

I get this error:

<img width="375" alt="screen shot 2017-03-23 at 10 28 13 pm" src="https://cloud.githubusercontent.com/assets/6282681/24278132/40bfc484-1018-11e7-97b4-49570562b7dd.png">

These are the commands I've run:
```bash
npm i -S gl-react
npm i -S gl-react-native & rnpm link
npm i -S react-native-image-cropper
```

Here are my package versions:
```bash
$ npm -v
4.1.2
$ npm ls react-native gl-react gl-react-native react-native-image-cropper
app@0.0.1 /Users/bkotos/Projects/react-native/app
├── gl-react@2.2.10
├── gl-react-native@3.0.0-alpha.5
├── react-native@0.41.2
└─┬ react-native-image-cropper@0.3.0
  └── gl-react-native@2.42.1
```

I also went through the setup steps in [gl-react-native](https://github.com/ProjectSeptemberInc/gl-react-native) and added `libRNGL.a` to the build phase in my app's xcode project.  This didn't help either.

Am I doing something wrong or possibly missing a step in the setup?

**Comment by imbudhiraja** [comment]
Hi @stoffern @NISHANTSINGHREWSAN @ignivarahulsaini
I have tested and found the problem is with gl-react-native. when we run npm install and files of package not downloaded. i have downlaoded them mannully and run run install with files it worked.

**Comment by bkotos** [comment]
@imbudhiraja thanks for this insight.  Which files specifically need to be manually downloaded?

**Comment by matjemeisje** [comment]
I had the same problem, but solved it by first uninstalling both `gl-react-native` and `react-native-image-cropper` and then reinstalling as such:
`npm i -S gl-react-native@2.42.1`
`react-native link gl-react-native`
`npm i -S react-native-image-cropper`

**Comment by bkotos** [comment]
@matjemeisje this did the trick.  Thank you!

**Comment by MAXMASTER001** [comment]
I am having the same error on the android side.  couldn't find a solution yet.
