### ISSUE TITLE
getting error unable to run

### ISSUE THREAD

**Issue by NISHANTSINGHREWSAN** [stoffern/react-native-image-cropper#33]
i am using these dependencies

"dependencies": {
"gl-react": "^2.2.9",
"gl-react-native": "^2.40.2",
"querystring": "^0.2.0",
"react": "^0.14.8",
"react-native": "^0.24.1",

}

**Comment by ignivarahulsaini** [comment]
Please give more information @NISHANTSINGHREWSAN

**Comment by imbudhiraja** [comment]
Hi @stoffern @NISHANTSINGHREWSAN @ignivarahulsaini 
I have tested and found the problem is with gl-react-native. when we run npm install and files of package not downloaded. i have downlaoded them mannully and run run install with files it worked.

**Comment by stoffern** [comment]
@NISHANTSINGHREWSAN I can not se any error messages or any problems in your description.
How am i supposed to find the problem?
