### ISSUE TITLE
Add filePath property to persist cropped image to disk

### ISSUE THREAD

**Issue by freakyfriday** [stoffern/react-native-image-cropper#36]
The captureFrame method of Surface in gl-react-native has the ability to specify file as a format and filePath to persist the cropped image to disk/storage.

Update line 196 in ImageCrop.js to:
return this.refs.cropit.captureFrame({quality: this.props.quality, type: this.props.type, format: this.props.format, **filePath: this.props.filePath**})

Example usage:
let filepath = `${RNFetchBlob.fs.dirs.CacheDir}/temp_post_image.jpg`;

<ImageCrop 
                          ref         = {'cropper'}
                          format      = {'file'}
                          filePath    = {filepath}
                          image       = {this.state.image}
                          cropHeight  = {Screen.width}
                          cropWidth   = {Screen.width}
                          type        = 'jpg'
                          quality     = {0.6}
                          maxZoom     = {80}
                          minZoom     = {20}
                          panToMove   = {true}
                          pinchToZoom = {true}
                        />

**Comment by stoffern** [comment]
feature added 
https://github.com/stoffern/react-native-image-cropper/blob/master/src/ImageCrop.js#L195
