### ISSUE TITLE
Issue with photos in portrait format

### ISSUE THREAD

**Issue by pi-sw** [stoffern/react-native-image-cropper#37]
First of all, great library - thanks!

However, I noticed a problem with photos in portrait format (width < height). 

I load the default photos from the simulator's camera roll. **Landscape** photos are fine, but **portrait** photos are not displayed in the `ImageCrop` component. 

Tweaking the `cropWidth` and/or `cropHeight` does not have any effect. 
Do you have any special handling for that?

**Comment by stoffern** [comment]
can you provide a sample repo?

**Comment by stoffern** [comment]
closed due to inactivity
