### ISSUE TITLE
App crashes when trying to load a new image

### ISSUE THREAD

**Issue by saahilp** [stoffern/react-native-image-cropper#47]
Hi, 

I am trying to load a new image whenever capture is clicked. However, the app crashes whenever the button is clicked. I am able to console log the URL of the image to be loaded, and the URL of the image is being loaded, but the app crashes whenever it tries to load the image. Also, if it matters, I'm trying to move on to the next element of an array to load an image. My initial image is files[0].link, and the next one is files[1].link which is where it crashes. I tried to look at the logs on Android Studio and it seems that there is some issue with gl-react-native. Any idea where the issue might be?

Thanks

**Comment by stoffern** [comment]
gave you a answer on FB..
