### ISSUE TITLE
Render image Without stretching 

### ISSUE THREAD

**Issue by anoopmm** [stoffern/react-native-image-cropper#48]
Is there any way to render uploaded images in different aspect ratios without stretching. Example ----
![screenshot_20171206-150732](https://user-images.githubusercontent.com/16194055/33655660-b3ddee4a-da99-11e7-8907-3f96346b0634.png)
 ?

**Comment by kytwb** [comment]
@stoffern any input on this or workaround?

**Comment by stoffern** [comment]
please setup a example repo..

**Comment by anoopmm** [comment]
This problem occurred me when i dynamically changes image url by setting state image={this.state.content.uri} . Then tried another way by hiding <Imagecrop/> component and shows again when i resetting url .now it works perfecly

**Comment by giraldogdiego** [comment]
Hi @anoopmm, how did you manage to solve this? I'm having the same issue in iOS, but I don't understand the workaround, thanks!

**Comment by kytwb** [comment]
@giraldogdiego set a variable to false in the state, update the image url, set the previous variable to true; use that variable to conditionally mount the image preview.
