### ISSUE TITLE
glsl issue

### ISSUE THREAD

**Issue by leuxcid** [stoffern/react-native-image-cropper#50]
Im trying to upgrade my app to react native 50, and after updating to the latest version of this plugin i am getting an error GLSL is only available in gl-react v2. What versions of gl react and gl react native should i be using?

I currently have
        "react": "16.0.0",
        "react-native": "0.50.4",
        "gl-react": "2.3.1",
        "gl-react-native": "2.47.0",
       "react-native-image-cropper": "^0.4.1",

<img width="387" alt="glsl" src="https://user-images.githubusercontent.com/33917459/33922295-a98cdcbe-df7e-11e7-81d2-fcf0264e256c.png">

**Comment by notme1994** [comment]
Hello
Downgrading react-native-image-cropper to version 0.4.0 solved the problem for me

**Comment by wmcbain** [comment]
@notme1994 That's not really helpful for anyone using React Native above 0.50 as that depends on React 16.

Seeing the same issue too here with the same exact error.

Trying to upgrade to React Native 0.50.3

**Comment by riftshock** [comment]
I agree with @wmcbain .. also encountering the same problem..

I think one work around, which I haven't tried, for now is downgrading **react-native-image cropper to version 0.4.0** then just manually edit the PropTypes of the packages under node modules which is too much of a hustle..

**Comment by stoffern** [comment]
holy smokes, will look into it today.
I guess it is the update of gl-react-image that is the problem.

**Comment by leuxcid** [comment]
Bug #49 comes back on 0.4.3

**Comment by stoffern** [comment]
Try latest, 0.4.4 should fix it 0ca54371d26fedf4367115486fc990f8825e1fc2
Moved gl-react-image into this repo and made a fix for it

**Comment by stoffern** [comment]
better?

**Comment by wmcbain** [comment]
This is what I get with 0.4.4:

<img width="391" alt="screen shot 2017-12-15 at 1 41 49 pm" src="https://user-images.githubusercontent.com/7080654/34055593-e3049cd6-e19d-11e7-816a-cfeaeb3b499c.png">

0.4.3 worked for me @leuxcid, you sure you were running with clean cache?

**Comment by stoffern** [comment]
This problem is solved now with latest version, remember to do 
```
rm -rf node_modules
npm i 
```
or
```
yarn install
```

**Comment by stoffern** [comment]
working on latest release
