### ISSUE TITLE
filePath must be defined when using 'file' format and be a non-empty string

### ISSUE THREAD

**Issue by kytwb** [stoffern/react-native-image-cropper#54]
Current default is `''` (empty string). Expecting for it to work with default value.

**Comment by stoffern** [comment]
Do you get this error using type: base64 ?

**Comment by kytwb** [comment]
@stoffern when using type: file

**Comment by stoffern** [comment]
ah, well a default filename would be `default.png` 😉 
Want to create a PR or should i?

**Comment by kytwb** [comment]
@stoffern going for it 👍

**Comment by stoffern** [comment]
👍 by the way. set it to `default.jpg` as `jpg` is default extension.

**Comment by kytwb** [comment]
@stoffern if I just set it to `default.jpg` by default, it'll produce:

> Could not write file: You don't have permission to save the file "default.jpg"

Should I go and add `react-native-fs` as a dependency to be able to use `TemporaryDirectoryPath`? Even this solution is iOS only. Would love your input on that 😉

**Comment by stoffern** [comment]
Well then i think we should let it be like it is.
The error description is precise and enough to work with.
