### ISSUE TITLE
ImageCrop image is not changing if second time load component

### ISSUE THREAD

**Issue by junaidsubhni** [stoffern/react-native-image-cropper#56]
I am trying to crop image from this tool second time but I am facing a problem that it always shows previous image loaded in ImageCrop tag. Can someone fix it please

**Comment by junaidsubhni** [comment]
I am passing image through navigation params

**Comment by stoffern** [comment]
Provide code

**Comment by junaidsubhni** [comment]
`constructor(props) {
    super(props);
    console.log('constructor');
    console.log(this.props.navigation.state.params.image);
    this.state = {
      image: this.props.navigation.state.params.image,
      height: 200,
      width: 200,
      zoom: 0,
      showNew: true,
      newImage: 'http://i.imgur.com/tCatS2c.jpg',
    };
  }
  render() {
    const { navigate } = this.props.navigation;
    return (
      <ScrollView>
        <View style={{padding:20}}>
          <ImageCrop
            ref={'cropper'}
            image={this.props.navigation.state.params.image}
            cropHeight={this.state.height}
            cropWidth={this.state.width}
            zoom={this.state.zoom}
            maxZoom={80}
            minZoom={20}
            panToMove={true}
            pinchToZoom={true}
          />
         </View>
        </View>
      </ScrollView>
    );
  }`

**Comment by junaidsubhni** [comment]
constructor(props) {
    super(props);
    console.log('constructor');
    console.log(this.props.navigation.state.params.image);
    this.state = {
      image: this.props.navigation.state.params.image,
      height: 200,
      width: 200,
      zoom: 0,
      showNew: true,
      newImage: 'http://i.imgur.com/tCatS2c.jpg',
    };
  }

  render() {
    const { navigate } = this.props.navigation;
    return (
      <ScrollView>
        <View style={{padding:20}}>
          <ImageCrop
            ref={'cropper'}
            image={this.props.navigation.state.params.image}
            cropHeight={this.state.height}
            cropWidth={this.state.width}
            zoom={this.state.zoom}
            maxZoom={80}
            minZoom={20}
            panToMove={true}
            pinchToZoom={true}
          />
          
        </View>
      </ScrollView>
    );
  }

**Comment by junaidsubhni** [comment]
I have double check the photo URI string. It is OK. Only the picture displayed to crop is old one and the picture is stuck. on pressing crop/capture button it crop the new image behind it.

**Comment by stoffern** [comment]
you are setting state here:
```js
  this.state = {
    image: this.props.navigation.state.params.image,
    height: 200,
    width: 200,
    zoom: 0,
    showNew: true,
    newImage: 'http://i.imgur.com/tCatS2c.jpg',
  };
```

if props change you dont update state, so that will lead to `image={this.state.image}` not updating

You should either use props or update state propperly read more on cycles here:https://reactjs.org/docs/react-component.html
```js
shouldComponentUpdate(nextProps, nextState){
  if  (nextProps.image !== this.state.image){
    this.setState({image: nextProps.image})
  }
}
```

**Comment by stoffern** [comment]
closed due to inactivity and no response
