### ISSUE TITLE
Resets the orientation

### ISSUE THREAD

**Issue by sksahil030** [stoffern/react-native-image-cropper#58]
Hi
I took an image from the camera (android), rotated it and saved to gallery.
Now when i choose the image using this plugin, the image is displayed with original orientation i.e, as it was taken from the camera (prior to the rotation).

**Comment by stoffern** [comment]
Sounds like you rotated the image without looking at the Exif config of the image.
The cropper does not rotate the image in any way. it displays the image the same way it is saved.
