### ISSUE TITLE
Image pixelated in ios

### ISSUE THREAD

**Issue by nakulkundaliya** [stoffern/react-native-image-cropper#59]
Hello 
I am using your lib for inline cropping like Instagram.
I am fetching one major issue with your lib. Image pixelated if we choose 4k or high resolution.

**Set Image in image View**
![image view](https://user-images.githubusercontent.com/15937642/35223488-8c8cbe42-ffa7-11e7-8490-cb02f71d1f88.png)

**Set image in ImageCrop View**
![imagecroper view](https://user-images.githubusercontent.com/15937642/35223510-9e2cc084-ffa7-11e7-9bbc-25890423c28d.png)

Here I attached some screenshot you can see. The image is pixelated in ImageCrop component.

 Please help me

Thanks

**Comment by stoffern** [comment]
stackoverflow or gl-react-native v2, please report bugs here on issues
