### ISSUE TITLE
TypeError: Cannot read property 'crop' of undefined

### ISSUE THREAD

**Issue by ChiranjeeviAdi** [stoffern/react-native-image-cropper#60]
Please check my code below,
/**
 * Sample React Native App
 * https://github.com/facebook/react-native
 * @flow
 */

import React, { Component } from 'react';
import {
  Platform,
  StyleSheet,
  Text,
  View,
  Button,
  Image
} from 'react-native';
var ImagePicker = require('react-native-image-picker');
import {ImageCrop} from 'react-native-image-cropper'

var options = {
  title: 'Select Avatar',
  customButtons: [
    {name: 'fb', title: 'Choose Photo from Facebook'},
  ],
  storageOptions: {
    skipBackup: true,
    path: 'images'
  },
  maxWidth:200,
  maxHeight: 200
};
const instructions = Platform.select({
  ios: 'Press Cmd+R to reload,\n' +
    'Cmd+D or shake for dev menu',
  android: 'Double tap R on your keyboard to reload,\n' +
    'Shake or press menu button for dev menu',
});

export default class App extends Component {
  state = {
    avatarSource:"",
    height:200,
    width:200,
    zoom:0,
    avatarUri:""
  }
  capture() {
console.log(this.refs.cropper);// Its retuning undefined 

     this.refs.cropper.crop()
  .then(base64 => console.log(base64))
  }
  getImageView() {
    var view=[];
    let cropper = null;
    if(this.state.avatarSource!=''){
    view.push(
          <View key={0}>
            
            <View >
            <ImageCrop 
              ref={'cropper'}
              image={this.state.avatarUri}
              cropHeight={this.state.height}
              cropWidth={this.state.width}
              zoom={this.state.zoom}
              maxZoom={80}
              minZoom={20}
              panToMove={true}
              pinchToZoom={true}
            />
            </View>
            <Text onPress={this.capture()}>Capture()</Text>
            <View>
            {cropper}
            </View>
          </View>
        );
    return view;
  
    }
    
  }
  componentWillMount() {
  }
  onPressLearnMore() {
    ImagePicker.showImagePicker(options, (response) => {
      console.log('Response = ', response);

      if (response.didCancel) {
        console.log('User cancelled image picker');
      }
      else if (response.error) {
        console.log('ImagePicker Error: ', response.error);
      }
      else if (response.customButton) {
        console.log('User tapped custom button: ', response.customButton);
      }
      else {
        let source = { uri: response.uri };

        // You can also display the image using data:
        // let source = { uri: 'data:image/jpeg;base64,' + response.data };

        this.setState({
          avatarSource: source,
          avatarUri:response.uri
        });
      }
    });

  }
  
  render() {
    return (
      <View style={styles.container}>
        <Text style={styles.welcome}>
          Welcome to React Native!
        </Text>
        <Text style={styles.instructions}>
          To get started, edit App.js
        </Text>
        <Text style={styles.instructions}>
          {instructions}
        </Text>
        <Button
          onPress={this.onPressLearnMore.bind(this)}
          title="Learn More"
          color="#841584"
          accessibilityLabel="Learn more about this purple button"
        />
        <View>
        {this.getImageView()}
        </View>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },
  uploadAvatar:{
    width: 200,
    height: 200
  }
});

**Comment by stoffern** [comment]
Stackoverflow. You need import on top of document!
