### ISSUE TITLE
PanResponder.onPanResponderMove not responding for pinch

### ISSUE THREAD

**Issue by weixingsun** [stoffern/react-native-image-cropper#8]
Hello, @stoffern 

I cannot get event that more than 2 touches in my app using RN0.29

PanResponder.create({
onPanResponderMove: (evt, gestureState){
if(evt.nativeEvent.touches.length<2) //move
//if(evt.nativeEvent.changedTouches.length<2) //also move?
else //pinch, this condition is never called.
}
...
})
//Is PanResponder changing the API ?
thanks very much!

**Comment by stoffern** [comment]
@weixingsun please provide more details, ios, android, code +
It should all work on RN 0.29

**Comment by stoffern** [comment]
@weixingsun did you solve this?

**Comment by weixingsun** [comment]
@stoffern sorry for late, I cannot make it works on both Android 6.0.1/iOS 9.3.3 device with my RN.29, which is very annoying. I have tried to clean node_modules folder and re-install with no luck. 
When doing some debugging, in PanResponder.onPanResponderMove function, evt.nativeEvent.touches never greater than 1.
Could you please share a working example code for pinching with PanResponder, I am very new to this function, thank you so much.

**Comment by weixingsun** [comment]
Here is my code, thanks a lot: 
https://github.com/weixingsun/share4discover/blob/43e3c2be87d6992051dea9f332a0eeab5bbbc8db/ui/ZoomableImage2.js

**Comment by stoffern** [comment]
@weixingsun this is not related to this repo as you are creating your own.
This would normally be a react-native question.

The answer is that you are using:
`evt.nativeEvent.touches` only main finger.
you should use:
`evt.nativeEvent.changedTouches` as this will register changes on the touch, when you use two fingers.

closing this as it is not related to the repo

**Comment by slorber** [comment]
@stoffern are you sure this solution really works? move event is not triggered for me whenever the panResponder has 2 fingers

https://react-native.canny.io/feature-requests/p/panresponderonpanrespondermove-not-responding-for-pinch

**Comment by Ovi** [comment]
It didn't work for me either. Any news on this yet?
