### ISSUE TITLE
react-native-image-cropper alternatives

### ISSUE THREAD

**Issue by gomes042** [stoffern/react-native-image-cropper#82]
Well, as some of you have noticed this module appears to be abandoned and currently has not had many updates. At the moment neither TypeScript support is offered. And as said in https://github.com/st0ffern/react-native-image-cropper/issues/71 there is a lack of maintainers to take care of this project yet. The idea of ​​this type of module for react-native is very good, as some types of applications need to crop images in a customizable way. So while this module is no longer active or maintained by someone with time to dedicate it, I felt the need to look for some alternatives and perhaps to know other packages with similar functionality.

Some alternatives:
- [react-native-simple-image-cropper](https://github.com/barrsan/react-native-simple-image-cropper)
- [react-native-image-crop-picker](https://github.com/ivpusic/react-native-image-crop-picker)
- [react-native-amazing-cropper](https://github.com/ggunti/react-native-amazing-cropper)

**Comment by 3GOMESz** [comment]
There is also https://github.com/DuDigital/react-native-zoomable-view but you need to implement the crop function manually.
