### ISSUE TITLE
 Module AppRegistry is not a registered callable module.

### ISSUE THREAD

**Issue by StevenKing9** [stoffern/react-native-image-cropper#9]
Requiring unknow moudle  "gl-react-image". if you are sure the moudle is there ,try.......

I can't find gl-react-image in node_moudles .

where can I find it?

**Comment by stoffern** [comment]
Type: npm i -S gl-react-image
Looks like it is missing in the dependency

**Comment by StevenKing9** [comment]
yes , I just find it :(https://www.npmjs.com/package/gl-react-image)

thank you very much~!
